name: sona
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependency_overrides:
  intl: ^0.20.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  chatview: ^2.4.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_calendar: ^28.1.37
  open_filex: ^4.5.0
  file_picker: ^8.1.3
  uuid: ^4.5.1
  mime: ^2.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  flutter_dotenv: ^5.2.1
  oauth2: ^2.0.3
  flutter_native_splash: ^2.4.2
  flutter_secure_storage: ^9.2.2
  flutter_markdown: ^0.7.4+1
  auto_route: ^9.2.2
  injector: ^4.0.0
  infinite_scroll_pagination: ^4.1.0
  stomp_dart_client: ^2.1.0
  http_image_provider: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13

flutter:
  assets:
    - .env
    - assets/
    - assets/images/

  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic