name: sona
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.9.0

#dependency_overrides:
#  intl: ^0.20.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  intl: any
  chatview: ^2.5.0
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  logger: ^2.6.1
  flutter_svg: ^2.2.0
  open_filex: ^4.7.0
  file_picker: ^10.3.2
  uuid: ^4.5.1
  mime: ^2.0.0
  image_picker: ^1.2.0
  flutter_dotenv: ^6.0.0
  oauth2: ^2.0.3
  flutter_secure_storage: ^9.2.4
  auto_route: ^10.1.2
  injector: ^4.0.0
  infinite_scroll_pagination: ^5.1.1
  stomp_dart_client: ^2.1.3
  http_image_provider: ^1.1.0
  syncfusion_flutter_calendar: ^30.2.7
  image_cropper: ^9.1.0
  firebase_messaging: ^16.0.0
  firebase_core: ^4.0.0
  flutter_local_notifications: ^19.4.1
  url_launcher: ^6.3.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flutter_rating_stars: ^1.1.0
  timezone: ^0.10.1
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/sona_logo_install.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: "#003F37" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/images/sona_logo_install.png" # For adaptive icons on Android

flutter:
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/

  uses-material-design: true

  fonts:
    - family: SonaIcons
      fonts:
        - asset: assets/SonaIcons.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic